//
//  StatementPresenter.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementPresentationLogic {
    func presentSomething(response: Statement.doLogout.Response)
}

class StatementPresenter: StatementPresentationLogic {
    weak var viewController: StatementDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Statement.doLogout.Response) {
        let viewModel = Statement.doLogout.ViewModel()
        viewController?.displayDoLogout(viewModel: viewModel)
    }
}
