//
//  StatementInteractor.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StatementBusinessLogic {
    func doLogout(request: Statement.doLogout.Request)
}

protocol StatementDataStore {
    var userData: UserData? {get set}
}

class StatementInteractor: StatementBusinessLogic, StatementDataStore {
    
    var presenter: StatementPresentationLogic?
    var worker: StatementWorker?
    var userData: UserData?
    
    // MARK: Do something
    
    func doLogout(request: Statement.doLogout.Request) {
        worker = StatementWorker()
        worker?.doSomeWork()
        
        let response = Statement.doLogout.Response()
        presenter?.presentSomething(response: response)
        
    }
}

