//
//  StatementRouter.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

    //MARK:- Protocol to do segue
protocol StatementRouterProtocol {
    func routeToLogin(segue: UIStoryboardSegue?)
//    func start()
    func setup() -> StatementViewController
}
    //MARK:- Stored data (interactor take this data and we can get)
protocol StatementDataPassingProtocol {
    var dataStore: StatementDataStoreProtocol? { get }
}

    // MARK:- Route
class StatementRouter: NSObject, StatementRouterProtocol, StatementDataPassingProtocol {
    
    var dataStore: StatementDataStoreProtocol?
    weak var viewController: StatementViewController?
    
    private let navigation: UINavigationController
    
    init(navigation: UINavigationController) {
        self.navigation = navigation
    }
    
    //MARK: - SETUP
    func setup() -> StatementViewController {
        let requesterHTTP = APIRequest()
        let utils = Utils()
        let worker = StatementWorker(apiRequester: requesterHTTP, utils: utils)
        let presenter = StatementPresenter()
        let interactor = StatementInteractor(worker: worker, presenter: presenter)
        let viewController = navigation.storyboard?.instantiateViewController(withIdentifier: "StatementViewController") as! StatementViewController
        viewController.interactor = interactor
        viewController.statementRouter = self
        let statementView = viewController.view as! StatementView
        viewController.statementView = statementView
        statementView.viewController = viewController
        presenter.viewController = viewController
        self.viewController = viewController
        self.dataStore = interactor
        return viewController
    }
    
    // MARK:- Do the segue
    func routeToLogin(segue: UIStoryboardSegue?) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "LoginViewController") as! LoginViewController
        navigateToLogin(source: viewController!, destination: destinationVC)
    }
    
    // MARK:- Do the navigation to next view controller
    func navigateToLogin(source: StatementViewController, destination: LoginViewController) {
        source.navigationController?.popViewController(animated: true)
    }
    
    // MARK:- Passing data to view controller
    func passDataToLogin(source: StatementDataStoreProtocol, destination: inout LoginDataStoreProtocol) {
    }
    
}
