//
//  LoginInteractor.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func doLogin(request: Login.doLogin.Request)
    func viewLoad(request: Login.loginView.Request)
    func swtVerifications(request: Login.swtVerification.Request)
    func biometricVerification()
}

protocol LoginDataStore {
    var userData: UserData? {get}
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    var userData: UserData?
    // MARK:- Do something
    
    func doLogin(request: Login.doLogin.Request) {
        worker = LoginWorker()
        worker?.doLogin(request.user, request.switchLogin, request.switchBiometric){ result in
            switch result {
            case.success(let userResult):
                self.userData = userResult
                self.presenter?.presentUserData(.init(user: self.userData!))
                return
            case.failure(let error):
                self.presenter?.presentLoginError(.init(error.localizedDescription))
                return
            }
        }
    }
    
    func viewLoad(request: Login.loginView.Request) {
        worker = LoginWorker()
        worker?.keyChainVerification(request.switchLogin, request.switchBiometric){ result in
            switch result{
                case.success(let user):
                    self.presenter?.presentKeyChainData(.init(user: user))
                    return
                case.failure(_):
                    return
            }
        }
    }
    
    func swtVerifications(request: Login.swtVerification.Request) {
        worker = LoginWorker()
        worker?.swtVerifications(type: request.type, swtEmail: request.switchLogin, swtBiometric: request.switchBiometric){result in
            switch result{
                case.success(let result):
                    self.presenter?.presentSwtVerification(.init(message: result))
                case .failure(let error):
                    self.presenter?.presentSwtVerification(.init(message: error.localizedDescription))
            }
            
        }
    }
    
    func biometricVerification() {
        worker = LoginWorker()
        worker?.biometricVerification(){result in
            switch result{
                case.success(let userLogin):
                    self.presenter?.presentBiometricVerification(.init(login: userLogin.login, password: userLogin.password))
                case.failure(let error):
                    self.presenter?.presentBiometricError(.init(error.localizedDescription))
                    
            }
            
        }
    }
    
}
