//
//  LoginPresenter.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

    //MARK:- Presenter Protocols - called in interactor
protocol LoginPresenterProtocol {
    func presentUserData(_ response: Login.doLogin.Response)
    func presentLoginError(_ error: String )
    func presentKeyChainData(_ response: Login.loginView.Response)
    func presentSwtVerification(_ response: Login.swtVerification.Response)
    func presentSwtVerificationError(_ error: String)
    func presentBiometricVerification(_ user: UserLogin)
    func presentBiometricError(_ error: String)
}

class LoginPresenter: LoginPresenterProtocol {
    
    init() { }
    
    //MARK:- Interactor Variables
    weak var viewController: LoginViewControllerProtocol?
    
    // MARK:- Interactor functions(reicive interactor/ pass to viewController)
    func presentUserData(_ response: Login.doLogin.Response) {
        let viewModel = Login.doLogin.ViewModel(user: response.user)
        viewController?.callDisplayUserData(viewModel: viewModel)
    }
    
    func presentLoginError(_ error: String) {
        viewController?.callDisplayError(error: error)
    }
    
    func presentKeyChainData(_ response: Login.loginView.Response) {
        let userLogin = Login.loginView.ViewModel(user: response.user)
        viewController?.callDisplayKeyChainData(userLogin: userLogin)
    }
    
    func presentSwtVerification(_ response: Login.swtVerification.Response) {
        viewController?.callDisplaySwtVerification(message: response.message)
    }
    
    func presentSwtVerificationError(_ error: String) {
        viewController?.callDisplaySwtVerification(message: error)
    }
    
    func presentBiometricVerification(_ user: UserLogin) {
        let user = Login.biometricVerification.ViewModel(user: user)
        viewController?.callDisplayBiometricVerification(user: user)
    }
    
    func presentBiometricError(_ error: String) {
        viewController?.callDisplayBiometricError(error: error)
    }
    

}
