//
//  LoginModels.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    // MARK: Use cases
    
    enum doLogin {
        struct Request {
            let user: UserLogin
            let switchLogin: Bool
            let switchBiometric: Bool
        }
        
        struct Response {
            let user: UserData
        }
        struct ViewModel {
            let user: UserData
        }
    }
    
    enum loginView {
        struct Request {
            let switchLogin: Bool
            let switchBiometric: Bool
        }
        
        struct Response {
            let user: UserLogin
        }
        
        struct ViewModel {
            let user: UserLogin
        }
    }
    
    enum swtVerification {
        struct Request {
            let type: String
            let switchLogin: Bool
            let switchBiometric: Bool
        }
        
        struct Response {
            let message: String
        }
        
        struct ViewModel {
            let message: String
        }
    }
}
