//
//  LoginPresenter.swift
//  SolutisTeste
//
//  Created by Virtual Machine on 16/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentUserData(_ response: Login.doLogin.Response)
    func presentLoginError(_ error: String )
    func presentKeyChainData(_ response: Login.loginView.Response)
    func presentSwtVerification(_ response: Login.swtVerification.Response)
    func presentSwtVerificationError(_ error: String)
    func presentBiometricVerification(_ user: UserLogin)
    func presentBiometricError(_ error: String)
}

class LoginPresenter: LoginPresentationLogic {
    
    var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentUserData(_ response: Login.doLogin.Response) {
        let viewModel = Login.doLogin.ViewModel(user: response.user)
        viewController?.displayUserData(viewModel: viewModel)
    }
    
    func presentLoginError(_ error: String) {
        viewController?.displayError(error: error)
    }
    
    func presentKeyChainData(_ response: Login.loginView.Response) {
        let userLogin = Login.loginView.ViewModel(user: response.user)
        viewController?.displayKeyChainData(userLogin: userLogin)
    }
    
    func presentSwtVerification(_ response: Login.swtVerification.Response) {
//        let message = Login.swtVerification.ViewModel(message: response.message)
        viewController?.displaySwtVerification(message: response.message)
    }
    
    func presentSwtVerificationError(_ error: String) {
//        let message = Login.swtVerification.ViewModel(message: error)
        viewController?.displaySwtVerification(message: error)
    }
    
    func presentBiometricVerification(_ user: UserLogin) {
        let user = Login.biometricVerification.ViewModel(user: user)
        viewController?.displayBiometricVerification(user: user)
    }
    
    func presentBiometricError(_ error: String) {
        viewController?.displayBiometricError(error: error)
    }
    

}
